
DROP TABLE IF EXISTS media CASCADE;
CREATE TABLE media (
id SERIAL PRIMARY KEY NOT NULL,
title VARCHAR(255) NOT NULL,
type VARCHAR(255) NOT NULL,
year VARCHAR(255) NOT NULL,
imdb_id VARCHAR(255) NOT NULL
)
