
DROP TABLE IF EXISTS reviews CASCADE;
CREATE TABLE reviews (
id SERIAL PRIMARY KEY NOT NULL,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
imdb_id VARCHAR(255) NOT NULL,
user_review TEXT NOT NULL,
user_rating INTEGER NOT NULL
);
